#
# Makefile
#

LINK_CIRCLE_HOME = ../..

OBJS	= main.o kernel.o linkhut.o

DEFINE += -DLINKHUT_AUDIO_PLATFORM_DUMMY

include $(LINK_CIRCLE_HOME)/Rules.mk

INCLUDE += -I $(LINK_HOME)/examples/linkaudio
